//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCT.WebReference.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/Container.asmx")]
        public string CCT_WebReference_CtosContainer_Container {
            get {
                return ((string)(this["CCT_WebReference_CtosContainer_Container"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/Quickgate.asmx")]
        public string CCT_WebReference_CtosQuickgate_QuickGate {
            get {
                return ((string)(this["CCT_WebReference_CtosQuickgate_QuickGate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/Flitting.asmx")]
        public string CCT_WebReference_CtosTransfer_Flitting {
            get {
                return ((string)(this["CCT_WebReference_CtosTransfer_Flitting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/Eir.asmx")]
        public string CCT_WebReference_CtosEirManage_Eir {
            get {
                return ((string)(this["CCT_WebReference_CtosEirManage_Eir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uport.cwcct.com/WebServices/PopedomService.asmx")]
        public string CCT_WebReference_PopedomReference_PopedomService {
            get {
                return ((string)(this["CCT_WebReference_PopedomReference_PopedomService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/PreEir.asmx")]
        public string CCT_WebReference_CtosPreEir_PreEir {
            get {
                return ((string)(this["CCT_WebReference_CtosPreEir_PreEir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.81:6666/outyard.asmx")]
        public string CCT_WebReference_CtosOutYard_OutYard {
            get {
                return ((string)(this["CCT_WebReference_CtosOutYard_OutYard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.11.51:9055/release.asmx")]
        public string CCT_WebReference_CtosRelease_Release {
            get {
                return ((string)(this["CCT_WebReference_CtosRelease_Release"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.150.1.153:8080/GangKouShuJuJiaoHuanWebService/SendGytJinChuGangCheRenYu" +
            "anXixi")]
        public string CCT_WebReference_GateDataSendReference_GangKouShuJuJiaoHuanServiceImplService {
            get {
                return ((string)(this["CCT_WebReference_GateDataSendReference_GangKouShuJuJiaoHuanServiceImplService"]));
            }
        }
    }
}
