//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace OCR.BLL.CtosWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SM001001OperationCompleted;
        
        private System.Threading.SendOrPostCallback SM001002OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007001OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007002OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007030OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007006OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007032OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007036OperationCompleted;
        
        private System.Threading.SendOrPostCallback CM005001OperationCompleted;
        
        private System.Threading.SendOrPostCallback VM002001OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007031OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007037OperationCompleted;
        
        private System.Threading.SendOrPostCallback OP007095OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://10.1.3.28:8688/OCRService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SM001001CompletedEventHandler SM001001Completed;
        
        /// <remarks/>
        public event SM001002CompletedEventHandler SM001002Completed;
        
        /// <remarks/>
        public event OP007001CompletedEventHandler OP007001Completed;
        
        /// <remarks/>
        public event OP007002CompletedEventHandler OP007002Completed;
        
        /// <remarks/>
        public event OP007030CompletedEventHandler OP007030Completed;
        
        /// <remarks/>
        public event OP007006CompletedEventHandler OP007006Completed;
        
        /// <remarks/>
        public event OP007032CompletedEventHandler OP007032Completed;
        
        /// <remarks/>
        public event OP007036CompletedEventHandler OP007036Completed;
        
        /// <remarks/>
        public event CM005001CompletedEventHandler CM005001Completed;
        
        /// <remarks/>
        public event VM002001CompletedEventHandler VM002001Completed;
        
        /// <remarks/>
        public event OP007031CompletedEventHandler OP007031Completed;
        
        /// <remarks/>
        public event OP007037CompletedEventHandler OP007037Completed;
        
        /// <remarks/>
        public event OP007095CompletedEventHandler OP007095Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SM001001", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SM001001(string paras) {
            object[] results = this.Invoke("SM001001", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SM001001Async(string paras) {
            this.SM001001Async(paras, null);
        }
        
        /// <remarks/>
        public void SM001001Async(string paras, object userState) {
            if ((this.SM001001OperationCompleted == null)) {
                this.SM001001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSM001001OperationCompleted);
            }
            this.InvokeAsync("SM001001", new object[] {
                        paras}, this.SM001001OperationCompleted, userState);
        }
        
        private void OnSM001001OperationCompleted(object arg) {
            if ((this.SM001001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SM001001Completed(this, new SM001001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SM001002", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SM001002(string paras) {
            object[] results = this.Invoke("SM001002", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SM001002Async(string paras) {
            this.SM001002Async(paras, null);
        }
        
        /// <remarks/>
        public void SM001002Async(string paras, object userState) {
            if ((this.SM001002OperationCompleted == null)) {
                this.SM001002OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSM001002OperationCompleted);
            }
            this.InvokeAsync("SM001002", new object[] {
                        paras}, this.SM001002OperationCompleted, userState);
        }
        
        private void OnSM001002OperationCompleted(object arg) {
            if ((this.SM001002Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SM001002Completed(this, new SM001002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007001", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007001(string paras) {
            object[] results = this.Invoke("OP007001", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007001Async(string paras) {
            this.OP007001Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007001Async(string paras, object userState) {
            if ((this.OP007001OperationCompleted == null)) {
                this.OP007001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007001OperationCompleted);
            }
            this.InvokeAsync("OP007001", new object[] {
                        paras}, this.OP007001OperationCompleted, userState);
        }
        
        private void OnOP007001OperationCompleted(object arg) {
            if ((this.OP007001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007001Completed(this, new OP007001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007002", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007002(string paras) {
            object[] results = this.Invoke("OP007002", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007002Async(string paras) {
            this.OP007002Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007002Async(string paras, object userState) {
            if ((this.OP007002OperationCompleted == null)) {
                this.OP007002OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007002OperationCompleted);
            }
            this.InvokeAsync("OP007002", new object[] {
                        paras}, this.OP007002OperationCompleted, userState);
        }
        
        private void OnOP007002OperationCompleted(object arg) {
            if ((this.OP007002Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007002Completed(this, new OP007002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007030", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007030(string paras) {
            object[] results = this.Invoke("OP007030", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007030Async(string paras) {
            this.OP007030Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007030Async(string paras, object userState) {
            if ((this.OP007030OperationCompleted == null)) {
                this.OP007030OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007030OperationCompleted);
            }
            this.InvokeAsync("OP007030", new object[] {
                        paras}, this.OP007030OperationCompleted, userState);
        }
        
        private void OnOP007030OperationCompleted(object arg) {
            if ((this.OP007030Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007030Completed(this, new OP007030CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007006", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007006(string paras) {
            object[] results = this.Invoke("OP007006", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007006Async(string paras) {
            this.OP007006Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007006Async(string paras, object userState) {
            if ((this.OP007006OperationCompleted == null)) {
                this.OP007006OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007006OperationCompleted);
            }
            this.InvokeAsync("OP007006", new object[] {
                        paras}, this.OP007006OperationCompleted, userState);
        }
        
        private void OnOP007006OperationCompleted(object arg) {
            if ((this.OP007006Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007006Completed(this, new OP007006CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007032", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007032(string paras) {
            object[] results = this.Invoke("OP007032", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007032Async(string paras) {
            this.OP007032Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007032Async(string paras, object userState) {
            if ((this.OP007032OperationCompleted == null)) {
                this.OP007032OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007032OperationCompleted);
            }
            this.InvokeAsync("OP007032", new object[] {
                        paras}, this.OP007032OperationCompleted, userState);
        }
        
        private void OnOP007032OperationCompleted(object arg) {
            if ((this.OP007032Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007032Completed(this, new OP007032CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007036", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007036(string paras) {
            object[] results = this.Invoke("OP007036", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007036Async(string paras) {
            this.OP007036Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007036Async(string paras, object userState) {
            if ((this.OP007036OperationCompleted == null)) {
                this.OP007036OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007036OperationCompleted);
            }
            this.InvokeAsync("OP007036", new object[] {
                        paras}, this.OP007036OperationCompleted, userState);
        }
        
        private void OnOP007036OperationCompleted(object arg) {
            if ((this.OP007036Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007036Completed(this, new OP007036CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CM005001", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CM005001(string paras) {
            object[] results = this.Invoke("CM005001", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CM005001Async(string paras) {
            this.CM005001Async(paras, null);
        }
        
        /// <remarks/>
        public void CM005001Async(string paras, object userState) {
            if ((this.CM005001OperationCompleted == null)) {
                this.CM005001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCM005001OperationCompleted);
            }
            this.InvokeAsync("CM005001", new object[] {
                        paras}, this.CM005001OperationCompleted, userState);
        }
        
        private void OnCM005001OperationCompleted(object arg) {
            if ((this.CM005001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CM005001Completed(this, new CM005001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VM002001", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VM002001(string paras) {
            object[] results = this.Invoke("VM002001", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VM002001Async(string paras) {
            this.VM002001Async(paras, null);
        }
        
        /// <remarks/>
        public void VM002001Async(string paras, object userState) {
            if ((this.VM002001OperationCompleted == null)) {
                this.VM002001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnVM002001OperationCompleted);
            }
            this.InvokeAsync("VM002001", new object[] {
                        paras}, this.VM002001OperationCompleted, userState);
        }
        
        private void OnVM002001OperationCompleted(object arg) {
            if ((this.VM002001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VM002001Completed(this, new VM002001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007031", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007031(string paras) {
            object[] results = this.Invoke("OP007031", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007031Async(string paras) {
            this.OP007031Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007031Async(string paras, object userState) {
            if ((this.OP007031OperationCompleted == null)) {
                this.OP007031OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007031OperationCompleted);
            }
            this.InvokeAsync("OP007031", new object[] {
                        paras}, this.OP007031OperationCompleted, userState);
        }
        
        private void OnOP007031OperationCompleted(object arg) {
            if ((this.OP007031Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007031Completed(this, new OP007031CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007037", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007037(string paras) {
            object[] results = this.Invoke("OP007037", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007037Async(string paras) {
            this.OP007037Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007037Async(string paras, object userState) {
            if ((this.OP007037OperationCompleted == null)) {
                this.OP007037OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007037OperationCompleted);
            }
            this.InvokeAsync("OP007037", new object[] {
                        paras}, this.OP007037OperationCompleted, userState);
        }
        
        private void OnOP007037OperationCompleted(object arg) {
            if ((this.OP007037Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007037Completed(this, new OP007037CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OP007095", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OP007095(string paras) {
            object[] results = this.Invoke("OP007095", new object[] {
                        paras});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OP007095Async(string paras) {
            this.OP007095Async(paras, null);
        }
        
        /// <remarks/>
        public void OP007095Async(string paras, object userState) {
            if ((this.OP007095OperationCompleted == null)) {
                this.OP007095OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOP007095OperationCompleted);
            }
            this.InvokeAsync("OP007095", new object[] {
                        paras}, this.OP007095OperationCompleted, userState);
        }
        
        private void OnOP007095OperationCompleted(object arg) {
            if ((this.OP007095Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OP007095Completed(this, new OP007095CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SM001001CompletedEventHandler(object sender, SM001001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SM001001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SM001001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SM001002CompletedEventHandler(object sender, SM001002CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SM001002CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SM001002CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007001CompletedEventHandler(object sender, OP007001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007002CompletedEventHandler(object sender, OP007002CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007002CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007002CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007030CompletedEventHandler(object sender, OP007030CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007030CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007030CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007006CompletedEventHandler(object sender, OP007006CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007006CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007006CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007032CompletedEventHandler(object sender, OP007032CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007032CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007032CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007036CompletedEventHandler(object sender, OP007036CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007036CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007036CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void CM005001CompletedEventHandler(object sender, CM005001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CM005001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CM005001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void VM002001CompletedEventHandler(object sender, VM002001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VM002001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VM002001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007031CompletedEventHandler(object sender, OP007031CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007031CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007031CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007037CompletedEventHandler(object sender, OP007037CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007037CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007037CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OP007095CompletedEventHandler(object sender, OP007095CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OP007095CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OP007095CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591