//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRX.Web.DAL.CtosWebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CtosWebReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 paras 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SM001001", ReplyAction="*")]
        OCRX.Web.DAL.CtosWebReference.SM001001Response SM001001(OCRX.Web.DAL.CtosWebReference.SM001001Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SM001001", ReplyAction="*")]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001001Response> SM001001Async(OCRX.Web.DAL.CtosWebReference.SM001001Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 paras 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SM001002", ReplyAction="*")]
        OCRX.Web.DAL.CtosWebReference.SM001002Response SM001002(OCRX.Web.DAL.CtosWebReference.SM001002Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SM001002", ReplyAction="*")]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001002Response> SM001002Async(OCRX.Web.DAL.CtosWebReference.SM001002Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 paras 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CM005001", ReplyAction="*")]
        OCRX.Web.DAL.CtosWebReference.CM005001Response CM005001(OCRX.Web.DAL.CtosWebReference.CM005001Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CM005001", ReplyAction="*")]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.CM005001Response> CM005001Async(OCRX.Web.DAL.CtosWebReference.CM005001Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 paras 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OP007095", ReplyAction="*")]
        OCRX.Web.DAL.CtosWebReference.OP007095Response OP007095(OCRX.Web.DAL.CtosWebReference.OP007095Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OP007095", ReplyAction="*")]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.OP007095Response> OP007095Async(OCRX.Web.DAL.CtosWebReference.OP007095Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SM001001Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SM001001", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.SM001001RequestBody Body;
        
        public SM001001Request() {
        }
        
        public SM001001Request(OCRX.Web.DAL.CtosWebReference.SM001001RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SM001001RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paras;
        
        public SM001001RequestBody() {
        }
        
        public SM001001RequestBody(string paras) {
            this.paras = paras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SM001001Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SM001001Response", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.SM001001ResponseBody Body;
        
        public SM001001Response() {
        }
        
        public SM001001Response(OCRX.Web.DAL.CtosWebReference.SM001001ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SM001001ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SM001001Result;
        
        public SM001001ResponseBody() {
        }
        
        public SM001001ResponseBody(string SM001001Result) {
            this.SM001001Result = SM001001Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SM001002Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SM001002", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.SM001002RequestBody Body;
        
        public SM001002Request() {
        }
        
        public SM001002Request(OCRX.Web.DAL.CtosWebReference.SM001002RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SM001002RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paras;
        
        public SM001002RequestBody() {
        }
        
        public SM001002RequestBody(string paras) {
            this.paras = paras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SM001002Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SM001002Response", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.SM001002ResponseBody Body;
        
        public SM001002Response() {
        }
        
        public SM001002Response(OCRX.Web.DAL.CtosWebReference.SM001002ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SM001002ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SM001002Result;
        
        public SM001002ResponseBody() {
        }
        
        public SM001002ResponseBody(string SM001002Result) {
            this.SM001002Result = SM001002Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CM005001Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CM005001", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.CM005001RequestBody Body;
        
        public CM005001Request() {
        }
        
        public CM005001Request(OCRX.Web.DAL.CtosWebReference.CM005001RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CM005001RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paras;
        
        public CM005001RequestBody() {
        }
        
        public CM005001RequestBody(string paras) {
            this.paras = paras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CM005001Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CM005001Response", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.CM005001ResponseBody Body;
        
        public CM005001Response() {
        }
        
        public CM005001Response(OCRX.Web.DAL.CtosWebReference.CM005001ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CM005001ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CM005001Result;
        
        public CM005001ResponseBody() {
        }
        
        public CM005001ResponseBody(string CM005001Result) {
            this.CM005001Result = CM005001Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OP007095Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OP007095", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.OP007095RequestBody Body;
        
        public OP007095Request() {
        }
        
        public OP007095Request(OCRX.Web.DAL.CtosWebReference.OP007095RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OP007095RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paras;
        
        public OP007095RequestBody() {
        }
        
        public OP007095RequestBody(string paras) {
            this.paras = paras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OP007095Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OP007095Response", Namespace="http://tempuri.org/", Order=0)]
        public OCRX.Web.DAL.CtosWebReference.OP007095ResponseBody Body;
        
        public OP007095Response() {
        }
        
        public OP007095Response(OCRX.Web.DAL.CtosWebReference.OP007095ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OP007095ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OP007095Result;
        
        public OP007095ResponseBody() {
        }
        
        public OP007095ResponseBody(string OP007095Result) {
            this.OP007095Result = OP007095Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : OCRX.Web.DAL.CtosWebReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<OCRX.Web.DAL.CtosWebReference.ServiceSoap>, OCRX.Web.DAL.CtosWebReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCRX.Web.DAL.CtosWebReference.SM001001Response OCRX.Web.DAL.CtosWebReference.ServiceSoap.SM001001(OCRX.Web.DAL.CtosWebReference.SM001001Request request) {
            return base.Channel.SM001001(request);
        }
        
        public string SM001001(string paras) {
            OCRX.Web.DAL.CtosWebReference.SM001001Request inValue = new OCRX.Web.DAL.CtosWebReference.SM001001Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.SM001001RequestBody();
            inValue.Body.paras = paras;
            OCRX.Web.DAL.CtosWebReference.SM001001Response retVal = ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).SM001001(inValue);
            return retVal.Body.SM001001Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001001Response> OCRX.Web.DAL.CtosWebReference.ServiceSoap.SM001001Async(OCRX.Web.DAL.CtosWebReference.SM001001Request request) {
            return base.Channel.SM001001Async(request);
        }
        
        public System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001001Response> SM001001Async(string paras) {
            OCRX.Web.DAL.CtosWebReference.SM001001Request inValue = new OCRX.Web.DAL.CtosWebReference.SM001001Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.SM001001RequestBody();
            inValue.Body.paras = paras;
            return ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).SM001001Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCRX.Web.DAL.CtosWebReference.SM001002Response OCRX.Web.DAL.CtosWebReference.ServiceSoap.SM001002(OCRX.Web.DAL.CtosWebReference.SM001002Request request) {
            return base.Channel.SM001002(request);
        }
        
        public string SM001002(string paras) {
            OCRX.Web.DAL.CtosWebReference.SM001002Request inValue = new OCRX.Web.DAL.CtosWebReference.SM001002Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.SM001002RequestBody();
            inValue.Body.paras = paras;
            OCRX.Web.DAL.CtosWebReference.SM001002Response retVal = ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).SM001002(inValue);
            return retVal.Body.SM001002Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001002Response> OCRX.Web.DAL.CtosWebReference.ServiceSoap.SM001002Async(OCRX.Web.DAL.CtosWebReference.SM001002Request request) {
            return base.Channel.SM001002Async(request);
        }
        
        public System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.SM001002Response> SM001002Async(string paras) {
            OCRX.Web.DAL.CtosWebReference.SM001002Request inValue = new OCRX.Web.DAL.CtosWebReference.SM001002Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.SM001002RequestBody();
            inValue.Body.paras = paras;
            return ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).SM001002Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCRX.Web.DAL.CtosWebReference.CM005001Response OCRX.Web.DAL.CtosWebReference.ServiceSoap.CM005001(OCRX.Web.DAL.CtosWebReference.CM005001Request request) {
            return base.Channel.CM005001(request);
        }
        
        public string CM005001(string paras) {
            OCRX.Web.DAL.CtosWebReference.CM005001Request inValue = new OCRX.Web.DAL.CtosWebReference.CM005001Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.CM005001RequestBody();
            inValue.Body.paras = paras;
            OCRX.Web.DAL.CtosWebReference.CM005001Response retVal = ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).CM005001(inValue);
            return retVal.Body.CM005001Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.CM005001Response> OCRX.Web.DAL.CtosWebReference.ServiceSoap.CM005001Async(OCRX.Web.DAL.CtosWebReference.CM005001Request request) {
            return base.Channel.CM005001Async(request);
        }
        
        public System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.CM005001Response> CM005001Async(string paras) {
            OCRX.Web.DAL.CtosWebReference.CM005001Request inValue = new OCRX.Web.DAL.CtosWebReference.CM005001Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.CM005001RequestBody();
            inValue.Body.paras = paras;
            return ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).CM005001Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCRX.Web.DAL.CtosWebReference.OP007095Response OCRX.Web.DAL.CtosWebReference.ServiceSoap.OP007095(OCRX.Web.DAL.CtosWebReference.OP007095Request request) {
            return base.Channel.OP007095(request);
        }
        
        public string OP007095(string paras) {
            OCRX.Web.DAL.CtosWebReference.OP007095Request inValue = new OCRX.Web.DAL.CtosWebReference.OP007095Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.OP007095RequestBody();
            inValue.Body.paras = paras;
            OCRX.Web.DAL.CtosWebReference.OP007095Response retVal = ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).OP007095(inValue);
            return retVal.Body.OP007095Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.OP007095Response> OCRX.Web.DAL.CtosWebReference.ServiceSoap.OP007095Async(OCRX.Web.DAL.CtosWebReference.OP007095Request request) {
            return base.Channel.OP007095Async(request);
        }
        
        public System.Threading.Tasks.Task<OCRX.Web.DAL.CtosWebReference.OP007095Response> OP007095Async(string paras) {
            OCRX.Web.DAL.CtosWebReference.OP007095Request inValue = new OCRX.Web.DAL.CtosWebReference.OP007095Request();
            inValue.Body = new OCRX.Web.DAL.CtosWebReference.OP007095RequestBody();
            inValue.Body.paras = paras;
            return ((OCRX.Web.DAL.CtosWebReference.ServiceSoap)(this)).OP007095Async(inValue);
        }
    }
}
